install.packages("tidyverse")
install.packages("janitor")
install.packages("highcharacter")
install.packages("knitr")
install.packages("lubridate")
install.packages("dplyr")
install.packages("tidyr")
install.packages("ggplot2")
library(tidyverse)
library(janitor)
library(knitr)
library(lubridate)
library(dplyr)
library(tidyr)
library(ggplot2)
daily_activity <- read.csv('dailyActivity_merged.csv')
glimpse(daily_activity)
tail(daily_activity)
view(daily_activity)
daily_activity %>%
  select(ActivityDate, TotalSteps,TotalDistance, SedentaryMinutes, Calories) %>%
  summary()
daily_activity <- clean_names(daily_activity)
daily_activity$activity_date <-mdy(daily_activity$activity_date)
sum(duplicated(daily_activity))
ggplot(daily_activity)+ geom_point(mapping = aes(x = total_steps, y = calories), color = "purple") +
  labs(x = "Total Steps", y = "Calories", title = "Total steps vs Calories spent")
view(daily_activity)
head(daily_activity)
ggplot(daily_activity)+ geom_point(mapping = aes(x = calories, y = sedentary_minutes), color = "green") +
  labs(x = "calories spent", y = "Sedentary minutes", title = "calories vs Sleep time")